config/routes.rb
Aiden::Application.routes.draw do

  resources :supermarkets do 
  	member do 
  		get 'google_map'
  	end
  	collection do
  		get 'search'
  	end
  end

  resources :products

  root :to => 'supermarkets#index'


end

app/models/location.rb
class Location < ActiveRecord::Base
	attr_accessible :name
	has_many :supermarkets
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price

  validates_presence_of :name, :price

  has_and_belongs_to_many :supermarkets
end

app/models/supermarket.rb
class Supermarket < ActiveRecord::Base
  attr_accessible :location, :name, :product_ids, :location_id

  validates_presence_of :location_id, :name
  validates_uniqueness_of :name

  has_and_belongs_to_many :products
  belongs_to :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/supermarkets_controller.rb
class SupermarketsController < ApplicationController

	def index
		@supermarkets = Supermarket.all
	end

	def google_map
		@supermarket = Supermarket.find(params[:id])
		render :layout => false
	end

	def edit
		@supermarket = Supermarket.find(params[:id])
		@products = Product.all
		respond_to do |format|
			format.js
		end
	end

	def update
		@supermarket = Supermarket.find(params[:id])
		if @supermarket.update_attributes(params[:supermarket])
			respond_to do |format|
				format.js
			end
		else
			render :action => :load_error
		end
	end

	def new
		@supermarket = Supermarket.new
		@products = Product.all
		respond_to do |format|
			format.js
		end
	end

	def create
		@supermarket = Supermarket.new(params[:supermarket])
		if @supermarket.save
			respond_to do |format|
				format.js
			end
		else
			render :action => :load_error
		end
	end

	def load_error
	end

	def show
		@supermarket = Supermarket.find(params[:id])
		respond_to do |format|
			format.js
		end
	end

	def destroy
		@supermarket = Supermarket.find(params[:id])
		@supermarket.destroy
		respond_to do |format|
			format.js
		end
	end

	def search
		@supermarkets = Supermarket.where("name ILIKE ?", params[:search])
		respond_to do |format|
			format.js
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.haml
%nav.row
	.large-5.columns
		= link_to 'New Supermarket', new_supermarket_path, :remote => true, :class => 'button tiny radius'
		= link_to 'Search Supermarket by Location', search_supermarkets_path, :remote => true, :class => 'button tiny radius', :id => 'search_link'
	.large-3.columns
		= form_tag '/supermarkets/search', :method => :get, :remote => true, :id => 'search_form' do
			= text_field_tag 'search'
			= submit_tag 'Search'
	.large-4.columns

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aiden</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="row">
<nav>
	<%= render :partial => 'layouts/navbar' %>
</nav>
<div class='flasherrors'>
	<span class="flash"><%= flash[:error] %></span>
</div>
<%= yield %>

</body>
</html>

app/views/supermarkets/_form.html.haml
= form_for @supermarket, :remote => true do |f|
	= f.label :name
	= f.text_field :name, :autofocus => true
	= f.label :location
	= f.select :location_id, Location.all.collect { |l| [l.name, l.id] }, :include_blank => true
	- @products.each do |product|
		= check_box_tag 'supermarket[product_ids][]', product.id, @supermarket.products.include?(product)
		= product.name
		%br

	= f.submit

app/views/supermarkets/_products.html.erb
<% supermarket.products.each do |p| %>
<span><%= p.name %><%= ',' unless p == supermarket.products.last %></span>
<% end %>

app/views/supermarkets/_supermarket.html.haml
%li{:id => "supermarket_#{supermarket.id}", :class => "sm_lis"}
	= link_to supermarket.name, supermarket_path(supermarket), :remote => true, :class => "supermarket_show_buttons"
	= link_to "Delete", supermarket_path(supermarket), :method => :delete, :remote => true, :confirm => "Are you sure?", :class => "button tiny alert radius"
	= link_to "Edit", edit_supermarket_path(supermarket), :remote => true, :class => "button tiny success radius"
	%div= link_to((supermarket.location ? supermarket.location.name : "None"), google_map_supermarket_path(supermarket))
	%div{:id => "mkt_product_#{supermarket.id}"}

app/views/supermarkets/create.js.erb
$('.flasherrors').empty();
$('#all_supermarkets_ul').append("<%=j render :partial => 'supermarket', :locals => {:supermarket => @supermarket} %>");

app/views/supermarkets/destroy.js.erb
$('#supermarket_<%= @supermarket.id %>').remove();

app/views/supermarkets/edit.js.erb
$('#new_supermarket_form').empty();
$('#new_supermarket_form').append("<%=j render :partial => 'form', :locals => {:supermarket => @supermarket} %>");

app/views/supermarkets/google_map.html.erb
<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?hl=en&amp;safe=off&amp;client=firefox-a&amp;q=<%= @supermarket.location.name.gsub(/\s/, '+') %>&amp;ie=UTF8&amp;hq=&amp;hnear=<%= @supermarket.location.name.gsub(/\s/, '+') %>&amp;t=m&amp;z=11&amp;output=embed"></iframe>

app/views/supermarkets/index.html.haml
.row
	.large-3.columns
		#new_supermarket_form
	.large-9.columns
		#all_supermarkets_div
			%ul#all_supermarkets_ul
				= render :partial => 'supermarket', :collection => @supermarkets, :as => 'supermarket'

app/views/supermarkets/load_error.js.erb
$('.flasherrors').empty();
<% @supermarket.errors.full_messages.each do |e| %>
$('.flasherrors').append("<%=j e %> <br />");
<% end %>

app/views/supermarkets/new.js.erb
$('#new_supermarket_form').empty();
$('#new_supermarket_form').append("<%=j render :partial => 'form', :locals => {:supermarket => @supermarket} %>");

app/views/supermarkets/search.js.erb
$('.sm_lis').css({'background': 'none'});
<% @supermarkets.each do |supermarket| %>
$('#supermarket_<%= supermarket.id %>').css({'background': 'rgb(239,239,239'});
<% end %>

app/views/supermarkets/show.js.erb
$('#mkt_product_<%= @supermarket.id %>').empty();
$('#mkt_product_<%= @supermarket.id %>').append("<%=j render :partial => 'products', :locals => {:supermarket => @supermarket} %>");